# Generated by Django 4.2.29 on 2026-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("notice", "通知"),
                            ("activity", "活动"),
                            ("urgent", "紧急"),
                        ],
                        default="notice",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="已发布"),
                ),
                (
                    "publish_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="定时发布时间"),
                ),
                (
                    "is_withdrawn",
                    models.BooleanField(default=False, verbose_name="已撤回"),
                ),
                ("is_archived", models.BooleanField(default=False, verbose_name="已归档")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "db_table": "operation_announcement",
                "ordering": ["-publish_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64, verbose_name="操作类型")),
                ("detail", models.TextField(blank=True, verbose_name="详情")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
            ],
            options={
                "verbose_name": "系统日志",
                "verbose_name_plural": "系统日志",
                "db_table": "operation_system_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
