# Generated by Django 4.2.29 on 2026-04-10 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
