# Generated by Django 4.2.29 on 2026-04-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("service", "物业服务"),
                            ("environment", "环境卫生"),
                            ("security", "安全管理"),
                            ("facility", "设施设备"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="投诉类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(verbose_name="问题描述")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="相关证据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("handler_remark", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "投诉建议",
                "verbose_name_plural": "投诉建议",
                "db_table": "property_complaint",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepairOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="故障描述")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="现场图片"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="分配时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报修工单",
                "verbose_name_plural": "报修工单",
                "db_table": "property_repair_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "非常差"), (2, "差"), (3, "一般"), (4, "好"), (5, "非常好")],
                        verbose_name="评分",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="评价内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="property.repairorder",
                        verbose_name="关联工单",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务反馈",
                "verbose_name_plural": "服务反馈",
                "db_table": "property_service_feedback",
            },
        ),
    ]
