# Generated by Django 4.2.29 on 2026-04-10 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repairorder",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_repairs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指派员工",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_orders",
                to="users.property",
                verbose_name="报修房产",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="报修人",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="投诉人",
            ),
        ),
    ]
