# Generated by Django 4.2.29 on 2026-04-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.CharField(max_length=7, verbose_name="年份月份")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="应缴金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未缴费"),
                            ("paid", "已缴费"),
                            ("overdue", "已逾期"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="缴费时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "db_table": "finance_bill",
                "ordering": ["-year_month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("property_fee", "物业费"),
                            ("parking_fee", "停车费"),
                            ("water_fee", "水费"),
                            ("electricity_fee", "电费"),
                            ("gas_fee", "燃气费"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="计量单位")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "收费项目",
                "verbose_name_plural": "收费项目",
                "db_table": "finance_charge_item",
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="缴费金额"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("bank", "银行转账"),
                            ("cash", "现金"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(blank=True, max_length=100, verbose_name="交易流水号"),
                ),
                (
                    "payment_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="缴费时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="finance.bill",
                        verbose_name="关联账单",
                    ),
                ),
            ],
            options={
                "verbose_name": "缴费记录",
                "verbose_name_plural": "缴费记录",
                "db_table": "finance_payment_record",
                "ordering": ["-payment_time"],
            },
        ),
    ]
